/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * Blog platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Register a new user
 */
export const registerBodyUsernameMin = 3;

export const registerBodyPasswordMin = 6;



export const RegisterBody = zod.object({
  "username": zod.string().min(registerBodyUsernameMin),
  "email": zod.string(),
  "password": zod.string().min(registerBodyPasswordMin),
  "displayName": zod.string().optional()
})

export const RegisterResponse = zod.object({
  "user": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})
})


/**
 * @summary Log in
 */
export const LoginBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "user": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})
})


/**
 * @summary Log out
 */
export const LogoutResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary Get current authenticated user
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary List posts
 */
export const listPostsQueryPageDefault = 1;
export const listPostsQueryLimitDefault = 12;
export const listPostsQuerySortDefault = `newest`;

export const ListPostsQueryParams = zod.object({
  "page": zod.coerce.number().default(listPostsQueryPageDefault),
  "limit": zod.coerce.number().default(listPostsQueryLimitDefault),
  "search": zod.coerce.string().optional(),
  "category": zod.coerce.string().optional(),
  "tag": zod.coerce.string().optional(),
  "status": zod.enum(['draft', 'published']).optional(),
  "authorId": zod.coerce.number().optional(),
  "sort": zod.enum(['newest', 'oldest', 'popular', 'trending']).default(listPostsQuerySortDefault)
})

export const ListPostsResponse = zod.object({
  "posts": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary Create a new post (authors/owner only)
 */

export const createPostBodyStatusDefault = `draft`;
export const createPostBodyFeaturedDefault = false;

export const CreatePostBody = zod.object({
  "title": zod.string().min(1).max(150),
  "subtitle": zod.string().max(250).optional(),
  "content": zod.string(),
  "excerpt": zod.string().optional(),
  "coverImageUrl": zod.string().optional(),
  "status": zod.enum(['draft', 'published']).default(createPostBodyStatusDefault),
  "featured": zod.boolean().default(createPostBodyFeaturedDefault),
  "categoryId": zod.number().optional(),
  "tags": zod.array(zod.string()).max(5).optional()
})

export const CreatePostResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Get featured posts for hero section
 */
export const getFeaturedPostsQueryLimitDefault = 5;

export const GetFeaturedPostsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getFeaturedPostsQueryLimitDefault)
})

export const GetFeaturedPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetFeaturedPostsResponse = zod.array(GetFeaturedPostsResponseItem)


/**
 * @summary Get trending posts (most viewed/liked in last 7 days)
 */
export const getTrendingPostsQueryLimitDefault = 6;

export const GetTrendingPostsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getTrendingPostsQueryLimitDefault)
})

export const GetTrendingPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetTrendingPostsResponse = zod.array(GetTrendingPostsResponseItem)


/**
 * @summary Get overall blog statistics
 */
export const GetBlogStatsResponse = zod.object({
  "totalPosts": zod.number(),
  "totalViews": zod.number(),
  "totalLikes": zod.number(),
  "totalAuthors": zod.number(),
  "categoryBreakdown": zod.array(zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "count": zod.number()
}))
})


/**
 * @summary Get a post by id
 */
export const GetPostParams = zod.object({
  "id": zod.coerce.number()
})

export const GetPostResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "content": zod.string(),
  "excerpt": zod.string().nullish(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Update a post
 */
export const UpdatePostParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdatePostBody = zod.object({
  "title": zod.string().min(1).max(150).optional(),
  "subtitle": zod.string().max(250).nullish(),
  "content": zod.string().optional(),
  "excerpt": zod.string().optional(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']).optional(),
  "featured": zod.boolean().optional(),
  "categoryId": zod.number().nullish(),
  "tags": zod.array(zod.string()).max(5).optional()
})

// Hand-written (not orval-generated): silent partial update used by the
// editor's debounced autosave. Deliberately has no minimums — a 1-character
// draft must be able to save without tripping the publish-gate validation.
export const AutosavePostBody = zod.object({
  "title": zod.string().optional(),
  "subtitle": zod.string().nullish(),
  "content": zod.string().optional(),
  "excerpt": zod.string().optional(),
  "coverImageUrl": zod.string().nullish(),
  "categoryId": zod.number().nullish(),
  "tags": zod.array(zod.string()).max(5).optional()
})

export const UpdatePostResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Delete a post
 */
export const DeletePostParams = zod.object({
  "id": zod.coerce.number()
})

export const DeletePostResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary Get a post by slug
 */
export const GetPostBySlugParams = zod.object({
  "slug": zod.coerce.string()
})

export const GetPostBySlugResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "content": zod.string(),
  "excerpt": zod.string().nullish(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Like a post
 */
export const LikePostParams = zod.object({
  "id": zod.coerce.number()
})

export const LikePostResponse = zod.object({
  "liked": zod.boolean(),
  "likeCount": zod.number()
})


/**
 * @summary Bookmark a post
 */
export const BookmarkPostParams = zod.object({
  "id": zod.coerce.number()
})

export const BookmarkPostResponse = zod.object({
  "bookmarked": zod.boolean()
})


/**
 * @summary Get related posts
 */
export const GetRelatedPostsParams = zod.object({
  "id": zod.coerce.number()
})

export const getRelatedPostsQueryLimitDefault = 4;

export const GetRelatedPostsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getRelatedPostsQueryLimitDefault),
  "page": zod.coerce.number().default(1)
})

export const GetRelatedPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetRelatedPostsResponse = zod.object({
  "posts": zod.array(GetRelatedPostsResponseItem),
  "total": zod.number(),
  "page": zod.number(),
  "pageSize": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary List comments for a post
 */
export const ListCommentsParams = zod.object({
  "id": zod.coerce.number()
})

export const ListCommentsResponseItem = zod.object({
  "id": zod.number(),
  "postId": zod.number(),
  "userId": zod.number(),
  "content": zod.string(),
  "parentId": zod.number().nullish(),
  "createdAt": zod.string(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional()
})
export const ListCommentsResponse = zod.array(ListCommentsResponseItem)


/**
 * @summary Add a comment
 */
export const CreateCommentParams = zod.object({
  "id": zod.coerce.number()
})




export const CreateCommentBody = zod.object({
  "content": zod.string().min(1),
  "parentId": zod.number().optional()
})

export const CreateCommentResponse = zod.object({
  "id": zod.number(),
  "postId": zod.number(),
  "userId": zod.number(),
  "content": zod.string(),
  "parentId": zod.number().nullish(),
  "createdAt": zod.string(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional()
})


/**
 * @summary Delete a comment
 */
export const DeleteCommentParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCommentResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary List categories
 */
export const ListCategoriesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
})
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem)


/**
 * @summary Create a category (owner only)
 */
export const CreateCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().optional(),
  "icon": zod.string().optional(),
  "color": zod.string().optional()
})

export const CreateCategoryResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
})


/**
 * @summary Update a category
 */
export const UpdateCategoryParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateCategoryBody = zod.object({
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish()
})

export const UpdateCategoryResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
})


/**
 * @summary Delete a category
 */
export const DeleteCategoryParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCategoryResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary List all tags
 */
export const ListTagsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})
export const ListTagsResponse = zod.array(ListTagsResponseItem)


/**
 * @summary Get current user's bookmarked posts
 */
export const GetMyBookmarksResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetMyBookmarksResponse = zod.array(GetMyBookmarksResponseItem)


/**
 * @summary Get current user's posts
 */
export const GetMyPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetMyPostsResponse = zod.array(GetMyPostsResponseItem)


/**
 * @summary Update current user profile
 */
export const UpdateProfileBody = zod.object({
  "displayName": zod.string().optional(),
  "bio": zod.string().nullish(),
  "avatarUrl": zod.string().nullish()
})

export const UpdateProfileResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Get a public user profile
 */
export const GetUserProfileParams = zod.object({
  "username": zod.coerce.string()
})

export const GetUserProfileResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string(),
  "postCount": zod.number(),
  "totalViews": zod.number().optional(),
  "totalLikes": zod.number().optional()
})


// Hand-written (not orval-generated): Author Follow & Post Notification
// System. See prisma/schema.prisma (AuthorFollow, Notification models) and
// src/routes/follow.routes.ts for the matching endpoints.

/**
 * @summary Follow an author
 */
export const FollowAuthorParams = zod.object({
  "authorId": zod.coerce.number()
})

export const FollowAuthorResponse = zod.object({
  "following": zod.boolean(),
  "notificationEnabled": zod.boolean()
})


/**
 * @summary Unfollow an author
 */
export const UnfollowAuthorParams = zod.object({
  "authorId": zod.coerce.number()
})

export const UnfollowAuthorResponse = zod.object({
  "following": zod.boolean()
})


/**
 * @summary Get follow status for an author
 */
export const GetFollowStatusParams = zod.object({
  "authorId": zod.coerce.number()
})

export const GetFollowStatusResponse = zod.object({
  "following": zod.boolean(),
  "notificationEnabled": zod.boolean()
})


/**
 * @summary Enable/disable email notifications for a followed author
 */
export const UpdateNotificationPreferenceParams = zod.object({
  "authorId": zod.coerce.number()
})

export const UpdateNotificationPreferenceBody = zod.object({
  "enabled": zod.boolean()
})

export const UpdateNotificationPreferenceResponse = zod.object({
  "following": zod.boolean(),
  "notificationEnabled": zod.boolean()
})


/**
 * @summary Get the current user's followed authors
 */
export const GetFollowedAuthorsResponseItem = zod.object({
  "authorId": zod.number(),
  "authorName": zod.string(),
  "authorUsername": zod.string(),
  "authorAvatarUrl": zod.string().nullish(),
  "following": zod.boolean(),
  "notificationEnabled": zod.boolean()
})
export const GetFollowedAuthorsResponse = zod.array(GetFollowedAuthorsResponseItem)


/**
 * @summary Get the current user's global email notification preference
 */
export const GetNotificationSettingsResponse = zod.object({
  "emailNotificationsGlobal": zod.boolean()
})


/**
 * @summary Update the current user's global email notification preference
 */
export const UpdateNotificationSettingsBody = zod.object({
  "emailNotificationsGlobal": zod.boolean()
})

export const UpdateNotificationSettingsResponse = zod.object({
  "emailNotificationsGlobal": zod.boolean()
})


// Hand-written (not orval-generated): Admin Content Operations Console.
// See docs/admin-console-architecture-notes.md for the scope this was
// deliberately narrowed to (no Media entity, owner role reused as
// SUPER_ADMIN, Reports doubling as the Moderation Queue).

/**
 * @summary Update a user's account status (suspend/restrict/restore/delete)
 */
export const AdminUpdateUserStatusBody = zod.object({
  "status": zod.enum(['active', 'restricted', 'suspended', 'deleted']),
  "reason": zod.string().min(1, "A reason is required"),
  "durationHours": zod.number().positive().nullish(),
  "note": zod.string().optional()
})

/**
 * @summary Force logout a user (invalidate their active session)
 */
export const AdminForceLogoutBody = zod.object({
  "reason": zod.string().optional()
})

/**
 * @summary Change a user's role (e.g. verify a reader as an author)
 */
export const AdminUpdateUserRoleBody = zod.object({
  "role": zod.enum(['owner', 'author', 'reader']),
  "reason": zod.string().min(1, "A reason is required")
})

/**
 * @summary Remove or restore a post (moderation soft-delete)
 */
export const AdminUpdatePostStatusBody = zod.object({
  "action": zod.enum(['remove', 'restore']),
  "reason": zod.string().min(1, "A reason is required"),
  "note": zod.string().optional()
})

/**
 * @summary Submit a report against a user, post, or comment
 */
export const SubmitReportBody = zod.object({
  "targetType": zod.enum(['user', 'post', 'comment']),
  "targetId": zod.number(),
  "reason": zod.enum(['spam', 'harassment', 'hate', 'sexual', 'violence', 'fraud', 'copyright', 'illegal', 'impersonation', 'other']),
  "description": zod.string().max(2000).optional()
})

/**
 * @summary Take a moderation decision on a report
 */
export const AdminDecideReportBody = zod.object({
  "action": zod.enum(['assign', 'dismiss', 'escalate', 'remove_content', 'restore_content', 'restrict_user', 'suspend_user']),
  "reason": zod.string().optional(),
  "note": zod.string().optional(),
  "assignToId": zod.number().optional(),
  "durationHours": zod.number().positive().nullish()
})


