/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * Blog platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Register a new user
 */
export const registerBodyUsernameMin = 3;

export const registerBodyPasswordMin = 6;



export const RegisterBody = zod.object({
  "username": zod.string().min(registerBodyUsernameMin),
  "email": zod.string(),
  "password": zod.string().min(registerBodyPasswordMin),
  "displayName": zod.string().optional()
})

export const RegisterResponse = zod.object({
  "user": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})
})


/**
 * @summary Log in
 */
export const LoginBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "user": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})
})


/**
 * @summary Log out
 */
export const LogoutResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary Get current authenticated user
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary List posts
 */
export const listPostsQueryPageDefault = 1;
export const listPostsQueryLimitDefault = 12;
export const listPostsQuerySortDefault = `newest`;

export const ListPostsQueryParams = zod.object({
  "page": zod.coerce.number().default(listPostsQueryPageDefault),
  "limit": zod.coerce.number().default(listPostsQueryLimitDefault),
  "search": zod.coerce.string().optional(),
  "category": zod.coerce.string().optional(),
  "tag": zod.coerce.string().optional(),
  "status": zod.enum(['draft', 'published']).optional(),
  "authorId": zod.coerce.number().optional(),
  "sort": zod.enum(['newest', 'oldest', 'popular', 'trending']).default(listPostsQuerySortDefault)
})

export const ListPostsResponse = zod.object({
  "posts": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary Create a new post (authors/owner only)
 */

export const createPostBodyStatusDefault = `draft`;
export const createPostBodyFeaturedDefault = false;

export const CreatePostBody = zod.object({
  "title": zod.string().min(1),
  "content": zod.string(),
  "excerpt": zod.string().optional(),
  "coverImageUrl": zod.string().optional(),
  "status": zod.enum(['draft', 'published']).default(createPostBodyStatusDefault),
  "featured": zod.boolean().default(createPostBodyFeaturedDefault),
  "categoryId": zod.number().optional(),
  "tags": zod.array(zod.string()).optional()
})

export const CreatePostResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Get featured posts for hero section
 */
export const getFeaturedPostsQueryLimitDefault = 5;

export const GetFeaturedPostsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getFeaturedPostsQueryLimitDefault)
})

export const GetFeaturedPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetFeaturedPostsResponse = zod.array(GetFeaturedPostsResponseItem)


/**
 * @summary Get trending posts (most viewed/liked in last 7 days)
 */
export const getTrendingPostsQueryLimitDefault = 6;

export const GetTrendingPostsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getTrendingPostsQueryLimitDefault)
})

export const GetTrendingPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetTrendingPostsResponse = zod.array(GetTrendingPostsResponseItem)


/**
 * @summary Get overall blog statistics
 */
export const GetBlogStatsResponse = zod.object({
  "totalPosts": zod.number(),
  "totalViews": zod.number(),
  "totalLikes": zod.number(),
  "totalAuthors": zod.number(),
  "categoryBreakdown": zod.array(zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "count": zod.number()
}))
})


/**
 * @summary Get a post by id
 */
export const GetPostParams = zod.object({
  "id": zod.coerce.number()
})

export const GetPostResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "content": zod.string(),
  "excerpt": zod.string().nullish(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Update a post
 */
export const UpdatePostParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdatePostBody = zod.object({
  "title": zod.string().min(1).optional(),
  "content": zod.string().optional(),
  "excerpt": zod.string().optional(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']).optional(),
  "featured": zod.boolean().optional(),
  "categoryId": zod.number().nullish(),
  "tags": zod.array(zod.string()).optional()
})

export const UpdatePostResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Delete a post
 */
export const DeletePostParams = zod.object({
  "id": zod.coerce.number()
})

export const DeletePostResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary Get a post by slug
 */
export const GetPostBySlugParams = zod.object({
  "slug": zod.coerce.string()
})

export const GetPostBySlugResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "content": zod.string(),
  "excerpt": zod.string().nullish(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})


/**
 * @summary Like a post
 */
export const LikePostParams = zod.object({
  "id": zod.coerce.number()
})

export const LikePostResponse = zod.object({
  "liked": zod.boolean(),
  "likeCount": zod.number()
})


/**
 * @summary Bookmark a post
 */
export const BookmarkPostParams = zod.object({
  "id": zod.coerce.number()
})

export const BookmarkPostResponse = zod.object({
  "bookmarked": zod.boolean()
})


/**
 * @summary Get related posts
 */
export const GetRelatedPostsParams = zod.object({
  "id": zod.coerce.number()
})

export const getRelatedPostsQueryLimitDefault = 4;

export const GetRelatedPostsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getRelatedPostsQueryLimitDefault)
})

export const GetRelatedPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetRelatedPostsResponse = zod.array(GetRelatedPostsResponseItem)


/**
 * @summary List comments for a post
 */
export const ListCommentsParams = zod.object({
  "id": zod.coerce.number()
})

export const ListCommentsResponseItem = zod.object({
  "id": zod.number(),
  "postId": zod.number(),
  "userId": zod.number(),
  "content": zod.string(),
  "parentId": zod.number().nullish(),
  "createdAt": zod.string(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional()
})
export const ListCommentsResponse = zod.array(ListCommentsResponseItem)


/**
 * @summary Add a comment
 */
export const CreateCommentParams = zod.object({
  "id": zod.coerce.number()
})




export const CreateCommentBody = zod.object({
  "content": zod.string().min(1),
  "parentId": zod.number().optional()
})

export const CreateCommentResponse = zod.object({
  "id": zod.number(),
  "postId": zod.number(),
  "userId": zod.number(),
  "content": zod.string(),
  "parentId": zod.number().nullish(),
  "createdAt": zod.string(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional()
})


/**
 * @summary Delete a comment
 */
export const DeleteCommentParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCommentResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary List categories
 */
export const ListCategoriesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
})
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem)


/**
 * @summary Create a category (owner only)
 */
export const CreateCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().optional(),
  "icon": zod.string().optional(),
  "color": zod.string().optional()
})

export const CreateCategoryResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
})


/**
 * @summary Update a category
 */
export const UpdateCategoryParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateCategoryBody = zod.object({
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish()
})

export const UpdateCategoryResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
})


/**
 * @summary Delete a category
 */
export const DeleteCategoryParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCategoryResponse = zod.object({
  "success": zod.boolean()
})


/**
 * @summary List all tags
 */
export const ListTagsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})
export const ListTagsResponse = zod.array(ListTagsResponseItem)


/**
 * @summary Get current user's bookmarked posts
 */
export const GetMyBookmarksResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetMyBookmarksResponse = zod.array(GetMyBookmarksResponseItem)


/**
 * @summary Get current user's posts
 */
export const GetMyPostsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "slug": zod.string(),
  "excerpt": zod.string().nullable(),
  "coverImageUrl": zod.string().nullish(),
  "status": zod.enum(['draft', 'published']),
  "featured": zod.boolean().optional(),
  "authorId": zod.number(),
  "categoryId": zod.number().nullish(),
  "viewCount": zod.number().optional(),
  "likeCount": zod.number().optional(),
  "commentCount": zod.number().optional(),
  "readingTime": zod.number().optional(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "publishedAt": zod.string().nullish(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
}).optional(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "color": zod.string().nullish(),
  "postCount": zod.number().optional()
}).optional(),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string()
})).optional(),
  "isLiked": zod.boolean().optional(),
  "isBookmarked": zod.boolean().optional()
})
export const GetMyPostsResponse = zod.array(GetMyPostsResponseItem)


/**
 * @summary Update current user profile
 */
export const UpdateProfileBody = zod.object({
  "displayName": zod.string().optional(),
  "bio": zod.string().nullish(),
  "avatarUrl": zod.string().nullish()
})

export const UpdateProfileResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Get a public user profile
 */
export const GetUserProfileParams = zod.object({
  "username": zod.coerce.string()
})

export const GetUserProfileResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "displayName": zod.string().nullish(),
  "role": zod.enum(['owner', 'author', 'reader']),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "createdAt": zod.string(),
  "postCount": zod.number(),
  "totalViews": zod.number().optional(),
  "totalLikes": zod.number().optional()
})


