export const categoryMeta = {
  name: "Sports",
  slug: "sports",
  description: "Cricket, football, tennis, and athletics — the records that may never fall.",
};

export const urls = [
  "https://sandybrown-dotterel-689149.hostingersite.com/sachin-tendulkar-records-that-may-never-be-broken-in-cricket-history/",
  "https://sandybrown-dotterel-689149.hostingersite.com/virat-kohli-odi-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/jacques-kallis-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/rohit-sharma-records-that-may-never-be-broken-in-cricket-history/",
  "https://sandybrown-dotterel-689149.hostingersite.com/rahul-dravid-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/ms-dhoni-records-that-may-never-be-broken-in-cricket-history/",
  "https://sandybrown-dotterel-689149.hostingersite.com/team-india-first-team-to-achieve-these-historic-t20i-milestones/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-every-ball-cant-be-yorker-in-cricket/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-no-cricketer-can-play-200-test-matches-again/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-vaibhav-suryavanshi-cannot-play-another-u19-world-cup/",
  "https://sandybrown-dotterel-689149.hostingersite.com/top-10-hardest-bowling-records-in-cricket-history/",
  "https://sandybrown-dotterel-689149.hostingersite.com/hardest-batting-records-in-odi-and-test-cricket-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/hardest-fielding-records-in-odi-and-test-cricket-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/top-10-hardest-wicket-keeper-records-in-odi-and-test-cricket/",
  "https://sandybrown-dotterel-689149.hostingersite.com/top-10-ipl-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/3-team-india-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/australian-cricket-team-records/",
  "https://sandybrown-dotterel-689149.hostingersite.com/muttiah-muralitharan-1347-wickets-most-unbreakable-record/",
  "https://sandybrown-dotterel-689149.hostingersite.com/womens-odi-test-cricket-records-never-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/lionel-messi-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/cristiano-ronaldo-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-is-it-almost-impossible-to-win-every-match-in-the-fifa-world-cup/",
  "https://sandybrown-dotterel-689149.hostingersite.com/fifa-world-cup-records/",
  "https://sandybrown-dotterel-689149.hostingersite.com/fifa-world-cup-team-records/",
  "https://sandybrown-dotterel-689149.hostingersite.com/no-football-team-can-stay-dominant-forever/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-perfect-football-player-can-never-exist/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-three-consecutive-champions-league-titles-may-never-happen-again/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-scoring-in-every-football-match-is-impossible/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-1000-international-goals-is-nearly-impossible-in-football/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-100-percent-penalty-conversion-is-impossible-in-football/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-penalty-shootouts-can-never-be-truly-fair/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-perfect-goalkeeping-is-impossible-in-football/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-football-matches-cannot-be-completely-fair/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-offside-decisions-can-never-be-perfect-in-football/",
  "https://sandybrown-dotterel-689149.hostingersite.com/uefa-champions-league-records/",
  "https://sandybrown-dotterel-689149.hostingersite.com/novak-djokovic-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/roger-federer-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/rafael-nadal-records-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/10-unbreakable-records-in-womens-tennis-that-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-300-kmh-tennis-serve-is-almost-impossible/",
  "https://sandybrown-dotterel-689149.hostingersite.com/unbreakable-olympic-athletics-records/",
  "https://sandybrown-dotterel-689149.hostingersite.com/unbreakable-womens-olympic-athletics-records/",
  "https://sandybrown-dotterel-689149.hostingersite.com/why-usain-bolts-958-seconds-may-never-be-broken/",
  "https://sandybrown-dotterel-689149.hostingersite.com/tennis-player-dominate-every-surface/",
];
